<?php
	App::uses('AppController', 'Controller');

	/**
	 * Buildingspots Controller
	 *
	 * @property Buildingspot $Buildingspot
	 * @property PaginatorComponent $Paginator
	 */
	class BuildingspotsController extends AppController {

		/**
		 * Components
		 *
		 * @var array
		 */
		public $components = array('Paginator', 'Cakeular.Cakeular', 'Table');

		/**
		 * index method
		 *
		 * @return void
		 */
		public function index() {
			$this->layout = 'Cakeular.angular';
		}

		/**
		 * JSON API method
		 * generated by mcred/Cakeular Plugin
		 *
		 * @link          https://github.com/mcred/Cakeular
		 *
		 * @return void
		 * @throws exception
		 */
		public function api($id = null) {
			$method = isset($this->request->query["method"]) ? $this->request->query["method"]:null;
			$params = isset($this->request->query["params"]) ? $this->request->query["params"]:null;
			
			switch ($this->request->method()) {
				case 'GET':
					if (!$id) {

						if( isset($this->request->query["parent_field"]) && isset($this->request->query["parent_value"]) ) {
							try {
								$parentField = $this->request->query["parent_field"];
								$parentValue = $this->request->query["parent_value"];

								$this->Buildingspot->recursive = -1;
								$buildingspots = $this->Buildingspot->find('all', array(
									'conditions' => array(
										'Buildingspot.'. $parentField . ' LIKE ' => '%' . $parentValue . '%'
									)
								));
							}
							catch(Exception $ex) {
								$error = $this->Cakeular->error('failure',$ex->getMessage());
								$buildingspots = array('Buildingspot' => $error );
							}
						} 
		 				elseif($method != null)
						{
							try{
								$buildingspots = $this->$method( $params );				
								$this->set(compact('buildingspots'));
							}
							catch( Exception $ex ) {
								$error = $this->Cakeular->error( 'failure','Invalid Request Method : ' . $ex->getMessage() );
								$buildingspots = array(
									'Buildingspot' => $error
								);
							}
						} else {
							$parentObj = '';
							if(isset($this->request->query["parentObj"])) {
						    	$parentObj 	= $this->request->query["parentObj"];
						    }
						    $parentId = '';
						    if(isset($this->request->query["parentId"])) {
						    	$parentId	= $this->request->query["parentId"];
						    }
						    $this->Paginator->settings = array(
						    	'page' => $this->request->query["page"],
						        'limit' => $this->request->query["count"]
						    );
						    
						    //$buildingspots = $this->Paginator->paginate('Buildingspot');
						    
						    $conditions = array();

						    if($parentObj != '') {
						    	$conditions = array("`" . $parentObj . '`.`id` =' => $parentId);
						    }

	            			// CHANGE FOR THE DESIRED OUTPUT FIELDS ARRAY HERE...
						    $fields = array(
								'Buildingspot.id',
								'Buildingspot.createdAt',
								'Buildingspot.updatedAt',
								'Buildingspot.createdBy',
								'Buildingspot.updatedBy',
								'Building.name',
								'Buildingspot.building_id',
								'Buildingspot.name',
								'Buildingspot.spotNumber',
								'Buildingspot.lov_spot_section',
							);
					        $this->paginate = array(
					            'fields' => $fields,
					            'conditions' => $conditions
					        );		
			       			$this->Table->emptyElements = 0;
			       			// Change fields here...
					        $this->Table->fields = array($fields);

						    $buildingspots = $this->Table->getResponse();
						}

						$this->set(compact('buildingspots','id'));
					} elseif(!$this->Buildingspot->exists($id)){
						$error = $this->Cakeular->error('failure','The Buildingspot was not found');
						$buildingspot = array(
							'Buildingspot' => $error
						);
						$this->set(compact('buildingspot','id'));
					} else {
						$buildingspot = $this->Buildingspot->find('first', array('conditions' => array('Buildingspot.' . $this->Buildingspot->primaryKey => $id)));
						$this->set(compact('buildingspot','id'));
					}
					break;
				case 'POST':
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$buildingspots = array(
							'Buildingspot' => $error
						);
						$this->set(compact('buildingspots'));
						break;
					}
					$this->Buildingspot->create();
					try {
						if ($this->Buildingspot->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Buildingspot was added');
							$buildingspots = array(
								'Buildingspot' => $message,
								'id' => $this->Buildingspot->getLastInsertID()
							);
							$this->set(compact('buildingspots'));
						} else {
							$error = $this->Cakeular->error('failure','The Buildingspot was not saved');
							$buildingspots = array(
								'Buildingspot' => $error,
								'validationErrors' => $this->Buildingspot->validationErrors
							);
							$this->set(compact('buildingspots'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$buildingspots = array('Buildingspot' => $error );
						$this->set(compact('buildingspots','id'));
					}					
					break;
				case 'PUT':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$buildingspots = array(
							'Buildingspot' => $error
						);
						$this->set(compact('buildingspots'));
						break;
					}
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$buildingspots = array(
							'Buildingspot' => $error
						);
						$this->set(compact('buildingspots'));
						break;
					}
					try {
						if ($this->Buildingspot->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Buildingspot was updated');
							$buildingspot = array(
								'Buildingspot' => $message
							);
							$this->set(compact('buildingspot','id'));
						} else {
							$error = $this->Cakeular->error('failure','The Buildingspot was not saved');
							$buildingspot = array(
								'Buildingspot' => $error,
								'validationErrors' => $this->Buildingspot->validationErrors
							);
							$this->set(compact('buildingspot','id'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$buildingspot = array('Buildingspot' => $error );
						$this->set(compact('buildingspot','id'));
					}					
					break;
				case 'DELETE':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$buildingspots = array(
							'Buildingspot' => $error
						);
						$this->set(compact('buildingspots'));
						break;
					}
					$this->Buildingspot->id = $id;
					if ($this->Buildingspot->delete()) {
						$message = $this->Cakeular->message('success','The Buildingspot was deleted');
						$buildingspot = array(
							'Buildingspot' => $message
						);
					} else {
						$error = $this->Cakeular->error('failure','The Buildingspot was not deleted');
						$buildingspot = array(
							'Buildingspot' => $error
						);
					}
					$this->set(compact('buildingspot','id'));
					break;
				default:
					$error = $this->Cakeular->error('failure','Invalid Request Method');
					$buildingspot = array(
						'Buildingspot' => $error
					);
					$this->set(compact('buildingspot'));
					break;
			}
			$this->layout = 'ajax';
		}

	}
