<?php
	App::uses('AppController', 'Controller');

	/**
	 * Groups Controller
	 *
	 * @property Group $Group
	 * @property PaginatorComponent $Paginator
	 */
	class GroupsController extends AppController {

		/**
		 * Components
		 *
		 * @var array
		 */
		public $components = array('Paginator', 'Cakeular.Cakeular', 'Table');

		/**
		 * index method
		 *
		 * @return void
		 */
		public function index() {
			$this->layout = 'Cakeular.angular';
		}

		/**
		 * JSON API method
		 * generated by mcred/Cakeular Plugin
		 *
		 * @link          https://github.com/mcred/Cakeular
		 *
		 * @return void
		 * @throws exception
		 */
		public function api($id = null) {
			$method = isset($this->request->query["method"]) ? $this->request->query["method"]:null;
			$params = isset($this->request->query["params"]) ? $this->request->query["params"]:null;
			
			switch ($this->request->method()) {
				case 'GET':
					if (!$id) {

						if( isset($this->request->query["parent_field"]) && isset($this->request->query["parent_value"]) ) {
							try {
								$parentField = $this->request->query["parent_field"];
								$parentValue = $this->request->query["parent_value"];

								$this->Group->recursive = -1;
								$groups = $this->Group->find('all', array(
									'conditions' => array(
										'Group.'. $parentField . ' LIKE ' => '%' . $parentValue . '%'
									)
								));
							}
							catch(Exception $ex) {
								$error = $this->Cakeular->error('failure',$ex->getMessage());
								$groups = array('Group' => $error );
							}
						} 
		 				elseif($method != null)
						{
							try{
								$groups = $this->$method( $params );				
								$this->set(compact('groups'));
							}
							catch( Exception $ex ) {
								$error = $this->Cakeular->error( 'failure','Invalid Request Method : ' . $ex->getMessage() );
								$groups = array(
									'Group' => $error
								);
							}
						} else {
							$parentObj = '';
							if(isset($this->request->query["parentObj"])) {
						    	$parentObj 	= $this->request->query["parentObj"];
						    }
						    $parentId = '';
						    if(isset($this->request->query["parentId"])) {
						    	$parentId	= $this->request->query["parentId"];
						    }
						    $this->Paginator->settings = array(
						    	'page' => $this->request->query["page"],
						        'limit' => $this->request->query["count"]
						    );
						    
						    //$groups = $this->Paginator->paginate('Group');
						    
						    $conditions = array();

						    if($parentObj != '') {
						    	$conditions = array("`" . $parentObj . '`.`id` =' => $parentId);
						    }

	            			// CHANGE FOR THE DESIRED OUTPUT FIELDS ARRAY HERE...
						    $fields = array(
								'Group.createdAt',
								'Group.updatedAt',
								'Group.createdBy',
								'Group.updatedBy',
								'Group.name',
								'Group.lov_group_status',
								'Group.description',
								'Group.id',
							);
					        $this->paginate = array(
					            'fields' => $fields,
					            'conditions' => $conditions
					        );		
			       			$this->Table->emptyElements = 0;
			       			// Change fields here...
					        $this->Table->fields = array($fields);

						    $groups = $this->Table->getResponse();
						}

						$this->set(compact('groups','id'));
					} elseif(!$this->Group->exists($id)){
						$error = $this->Cakeular->error('failure','The Group was not found');
						$group = array(
							'Group' => $error
						);
						$this->set(compact('group','id'));
					} else {
						$group = $this->Group->find('first', array('conditions' => array('Group.' . $this->Group->primaryKey => $id)));
						$this->set(compact('group','id'));
					}
					break;
				case 'POST':
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$groups = array(
							'Group' => $error
						);
						$this->set(compact('groups'));
						break;
					}
					$this->Group->create();
					try {
						if ($this->Group->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Group was added');
							$groups = array(
								'Group' => $message,
								'id' => $this->Group->getLastInsertID()
							);
							$this->set(compact('groups'));
						} else {
							$error = $this->Cakeular->error('failure','The Group was not saved');
							$groups = array(
								'Group' => $error,
								'validationErrors' => $this->Group->validationErrors
							);
							$this->set(compact('groups'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$groups = array('Group' => $error );
						$this->set(compact('groups','id'));
					}					
					break;
				case 'PUT':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$groups = array(
							'Group' => $error
						);
						$this->set(compact('groups'));
						break;
					}
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$groups = array(
							'Group' => $error
						);
						$this->set(compact('groups'));
						break;
					}
					try {
						if ($this->Group->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Group was updated');
							$group = array(
								'Group' => $message
							);
							$this->set(compact('group','id'));
						} else {
							$error = $this->Cakeular->error('failure','The Group was not saved');
							$group = array(
								'Group' => $error,
								'validationErrors' => $this->Group->validationErrors
							);
							$this->set(compact('group','id'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$group = array('Group' => $error );
						$this->set(compact('group','id'));
					}					
					break;
				case 'DELETE':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$groups = array(
							'Group' => $error
						);
						$this->set(compact('groups'));
						break;
					}
					$this->Group->id = $id;
					if ($this->Group->delete()) {
						$message = $this->Cakeular->message('success','The Group was deleted');
						$group = array(
							'Group' => $message
						);
					} else {
						$error = $this->Cakeular->error('failure','The Group was not deleted');
						$group = array(
							'Group' => $error
						);
					}
					$this->set(compact('group','id'));
					break;
				default:
					$error = $this->Cakeular->error('failure','Invalid Request Method');
					$group = array(
						'Group' => $error
					);
					$this->set(compact('group'));
					break;
			}
			$this->layout = 'ajax';
		}

	}
