<?php
	App::uses('AppController', 'Controller');

	/**
	 * Lovs Controller
	 *
	 * @property Lov $Lov
	 * @property PaginatorComponent $Paginator
	 */
	class LovsController extends AppController {

		/**
		 * Components
		 *
		 * @var array
		 */
		public $components = array('Paginator', 'Cakeular.Cakeular', 'Table');

		/**
		 * index method
		 *
		 * @return void
		 */
		public function index() {
			$this->layout = 'Cakeular.angular';
		}

		/**
		 * JSON API method
		 * generated by mcred/Cakeular Plugin
		 *
		 * @link          https://github.com/mcred/Cakeular
		 *
		 * @return void
		 * @throws exception
		 */
		public function api($id = null) {
			$method = isset($this->request->query["method"]) ? $this->request->query["method"]:null;
			$params = isset($this->request->query["params"]) ? $this->request->query["params"]:null;
			
			switch ($this->request->method()) {
				case 'GET':
					if (!$id) {

						if( isset($this->request->query["parent_field"]) && isset($this->request->query["parent_value"]) ) {
							try {
								$parentField = $this->request->query["parent_field"];
								$parentValue = $this->request->query["parent_value"];

								$this->Lov->recursive = -1;
								$lovs = $this->Lov->find('all', array(
									'conditions' => array(
										'Lov.'. $parentField . ' LIKE ' => '%' . $parentValue . '%'
									)
								));
							}
							catch(Exception $ex) {
								$error = $this->Cakeular->error('failure',$ex->getMessage());
								$lovs = array('Lov' => $error );
							}
						} 
		 				elseif($method != null)
						{
							try{
								$lovs = $this->$method( $params );				
								$this->set(compact('lovs'));
							}
							catch( Exception $ex ) {
								$error = $this->Cakeular->error( 'failure','Invalid Request Method : ' . $ex->getMessage() );
								$lovs = array(
									'Lov' => $error
								);
							}
						} else {
							$parentObj = '';
							if(isset($this->request->query["parentObj"])) {
						    	$parentObj 	= $this->request->query["parentObj"];
						    }
						    $parentId = '';
						    if(isset($this->request->query["parentId"])) {
						    	$parentId	= $this->request->query["parentId"];
						    }
						    $this->Paginator->settings = array(
						    	'page' => $this->request->query["page"],
						        'limit' => $this->request->query["count"]
						    );
						    
						    //$lovs = $this->Paginator->paginate('Lov');
						    
						    $conditions = array();

						    if($parentObj != '') {
						    	$conditions = array("`" . $parentObj . '`.`id` =' => $parentId);
						    }

	            			// CHANGE FOR THE DESIRED OUTPUT FIELDS ARRAY HERE...
						    $fields = array(
								'Lov.createdAt',
								'Lov.updatedAt',
								'Lov.createdBy',
								'Lov.updatedBy',
								'Lov.orderShow',
								'Lov.lovType',
								'Lov.name_',
								'Lov.name_es_MX',
								'Lov.name_en_US',
								'Lov.status',
								'Parent.name',
								'Lov.parent_id',
								'Lov.id',
							);
					        $this->paginate = array(
					            'fields' => $fields,
					            'conditions' => $conditions
					        );		
			       			$this->Table->emptyElements = 0;
			       			// Change fields here...
					        $this->Table->fields = array($fields);

						    $lovs = $this->Table->getResponse();
						}

						$this->set(compact('lovs','id'));
					} elseif(!$this->Lov->exists($id)){
						$error = $this->Cakeular->error('failure','The Lov was not found');
						$lov = array(
							'Lov' => $error
						);
						$this->set(compact('lov','id'));
					} else {
						$lov = $this->Lov->find('first', array('conditions' => array('Lov.' . $this->Lov->primaryKey => $id)));
						$this->set(compact('lov','id'));
					}
					break;
				case 'POST':
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$lovs = array(
							'Lov' => $error
						);
						$this->set(compact('lovs'));
						break;
					}
					$this->Lov->create();
					try {
						if ($this->Lov->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Lov was added');
							$lovs = array(
								'Lov' => $message,
								'id' => $this->Lov->getLastInsertID()
							);
							$this->set(compact('lovs'));
						} else {
							$error = $this->Cakeular->error('failure','The Lov was not saved');
							$lovs = array(
								'Lov' => $error,
								'validationErrors' => $this->Lov->validationErrors
							);
							$this->set(compact('lovs'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$lovs = array('Lov' => $error );
						$this->set(compact('lovs','id'));
					}					
					break;
				case 'PUT':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$lovs = array(
							'Lov' => $error
						);
						$this->set(compact('lovs'));
						break;
					}
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$lovs = array(
							'Lov' => $error
						);
						$this->set(compact('lovs'));
						break;
					}
					try {
						if ($this->Lov->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Lov was updated');
							$lov = array(
								'Lov' => $message
							);
							$this->set(compact('lov','id'));
						} else {
							$error = $this->Cakeular->error('failure','The Lov was not saved');
							$lov = array(
								'Lov' => $error,
								'validationErrors' => $this->Lov->validationErrors
							);
							$this->set(compact('lov','id'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$lov = array('Lov' => $error );
						$this->set(compact('lov','id'));
					}					
					break;
				case 'DELETE':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$lovs = array(
							'Lov' => $error
						);
						$this->set(compact('lovs'));
						break;
					}
					$this->Lov->id = $id;
					if ($this->Lov->delete()) {
						$message = $this->Cakeular->message('success','The Lov was deleted');
						$lov = array(
							'Lov' => $message
						);
					} else {
						$error = $this->Cakeular->error('failure','The Lov was not deleted');
						$lov = array(
							'Lov' => $error
						);
					}
					$this->set(compact('lov','id'));
					break;
				default:
					$error = $this->Cakeular->error('failure','Invalid Request Method');
					$lov = array(
						'Lov' => $error
					);
					$this->set(compact('lov'));
					break;
			}
			$this->layout = 'ajax';
		}

	}
