<?php
	App::uses('AppController', 'Controller');

	/**
	 * Requests Controller
	 *
	 * @property Request $Request
	 * @property PaginatorComponent $Paginator
	 */
	class RequestsController extends AppController {

		/**
		 * Components
		 *
		 * @var array
		 */
		public $components = array('Paginator', 'Cakeular.Cakeular', 'Table');

		/**
		 * index method
		 *
		 * @return void
		 */
		public function index() {
			$this->layout = 'Cakeular.angular';
		}

		/**
		 * JSON API method
		 * generated by mcred/Cakeular Plugin
		 *
		 * @link          https://github.com/mcred/Cakeular
		 *
		 * @return void
		 * @throws exception
		 */
		public function api($id = null) {
			$method = isset($this->request->query["method"]) ? $this->request->query["method"]:null;
			$params = isset($this->request->query["params"]) ? $this->request->query["params"]:null;
			
			switch ($this->request->method()) {
				case 'GET':
					if (!$id) {

						if( isset($this->request->query["parent_field"]) && isset($this->request->query["parent_value"]) ) {
							try {
								$parentField = $this->request->query["parent_field"];
								$parentValue = $this->request->query["parent_value"];

								$this->Request->recursive = -1;
								$requests = $this->Request->find('all', array(
									'conditions' => array(
										'Request.'. $parentField . ' LIKE ' => '%' . $parentValue . '%'
									)
								));
							}
							catch(Exception $ex) {
								$error = $this->Cakeular->error('failure',$ex->getMessage());
								$requests = array('Request' => $error );
							}
						} 
		 				elseif($method != null)
						{
							try{
								$requests = $this->$method( $params );				
								$this->set(compact('requests'));
							}
							catch( Exception $ex ) {
								$error = $this->Cakeular->error( 'failure','Invalid Request Method : ' . $ex->getMessage() );
								$requests = array(
									'Request' => $error
								);
							}
						} else {
							$parentObj = '';
							if(isset($this->request->query["parentObj"])) {
						    	$parentObj 	= $this->request->query["parentObj"];
						    }
						    $parentId = '';
						    if(isset($this->request->query["parentId"])) {
						    	$parentId	= $this->request->query["parentId"];
						    }
						    $this->Paginator->settings = array(
						    	'page' => $this->request->query["page"],
						        'limit' => $this->request->query["count"]
						    );
						    
						    //$requests = $this->Paginator->paginate('Request');
						    
						    $conditions = array();

						    if($parentObj != '') {
						    	$conditions = array("`" . $parentObj . '`.`id` =' => $parentId);
						    }

	            			// CHANGE FOR THE DESIRED OUTPUT FIELDS ARRAY HERE...
						    $fields = array(
								'Request.createdAt',
								'Request.updatedAt',
								'Request.createdBy',
								'Request.updatedBy',
								'Request.name',
								'Request.description',
								'Request.lov_request_status',
								'Request.lov_request_type',
								'Request.lov_request_subtype',
								'Request.lov_request_priority',
								'Request.lov_request_severity',
								'Request.owner',
								'Request.id',
							);
					        $this->paginate = array(
					            'fields' => $fields,
					            'conditions' => $conditions
					        );		
			       			$this->Table->emptyElements = 0;
			       			// Change fields here...
					        $this->Table->fields = array($fields);

						    $requests = $this->Table->getResponse();
						}

						$this->set(compact('requests','id'));
					} elseif(!$this->Request->exists($id)){
						$error = $this->Cakeular->error('failure','The Request was not found');
						$request = array(
							'Request' => $error
						);
						$this->set(compact('request','id'));
					} else {
						$request = $this->Request->find('first', array('conditions' => array('Request.' . $this->Request->primaryKey => $id)));
						$this->set(compact('request','id'));
					}
					break;
				case 'POST':
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$requests = array(
							'Request' => $error
						);
						$this->set(compact('requests'));
						break;
					}
					$this->Request->create();
					try {
						if ($this->Request->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Request was added');
							$requests = array(
								'Request' => $message,
								'id' => $this->Request->getLastInsertID()
							);
							$this->set(compact('requests'));
						} else {
							$error = $this->Cakeular->error('failure','The Request was not saved');
							$requests = array(
								'Request' => $error,
								'validationErrors' => $this->Request->validationErrors
							);
							$this->set(compact('requests'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$requests = array('Request' => $error );
						$this->set(compact('requests','id'));
					}					
					break;
				case 'PUT':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$requests = array(
							'Request' => $error
						);
						$this->set(compact('requests'));
						break;
					}
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$requests = array(
							'Request' => $error
						);
						$this->set(compact('requests'));
						break;
					}
					try {
						if ($this->Request->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Request was updated');
							$request = array(
								'Request' => $message
							);
							$this->set(compact('request','id'));
						} else {
							$error = $this->Cakeular->error('failure','The Request was not saved');
							$request = array(
								'Request' => $error,
								'validationErrors' => $this->Request->validationErrors
							);
							$this->set(compact('request','id'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$request = array('Request' => $error );
						$this->set(compact('request','id'));
					}					
					break;
				case 'DELETE':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$requests = array(
							'Request' => $error
						);
						$this->set(compact('requests'));
						break;
					}
					$this->Request->id = $id;
					if ($this->Request->delete()) {
						$message = $this->Cakeular->message('success','The Request was deleted');
						$request = array(
							'Request' => $message
						);
					} else {
						$error = $this->Cakeular->error('failure','The Request was not deleted');
						$request = array(
							'Request' => $error
						);
					}
					$this->set(compact('request','id'));
					break;
				default:
					$error = $this->Cakeular->error('failure','Invalid Request Method');
					$request = array(
						'Request' => $error
					);
					$this->set(compact('request'));
					break;
			}
			$this->layout = 'ajax';
		}

	}
