<?php
	App::uses('AppController', 'Controller');

	/**
	 * Roles Controller
	 *
	 * @property Role $Role
	 * @property PaginatorComponent $Paginator
	 */
	class RolesController extends AppController {

		/**
		 * Components
		 *
		 * @var array
		 */
		public $components = array('Paginator', 'Cakeular.Cakeular', 'Table');

		/**
		 * index method
		 *
		 * @return void
		 */
		public function index() {
			$this->layout = 'Cakeular.angular';
		}

		/**
		 * JSON API method
		 * generated by mcred/Cakeular Plugin
		 *
		 * @link          https://github.com/mcred/Cakeular
		 *
		 * @return void
		 * @throws exception
		 */
		public function api($id = null) {
			$method = isset($this->request->query["method"]) ? $this->request->query["method"]:null;
			$params = isset($this->request->query["params"]) ? $this->request->query["params"]:null;
			
			switch ($this->request->method()) {
				case 'GET':
					if (!$id) {

						if( isset($this->request->query["parent_field"]) && isset($this->request->query["parent_value"]) ) {
							try {
								$parentField = $this->request->query["parent_field"];
								$parentValue = $this->request->query["parent_value"];

								$this->Role->recursive = -1;
								$roles = $this->Role->find('all', array(
									'conditions' => array(
										'Role.'. $parentField . ' LIKE ' => '%' . $parentValue . '%'
									)
								));
							}
							catch(Exception $ex) {
								$error = $this->Cakeular->error('failure',$ex->getMessage());
								$roles = array('Role' => $error );
							}
						} 
		 				elseif($method != null)
						{
							try{
								$roles = $this->$method( $params );				
								$this->set(compact('roles'));
							}
							catch( Exception $ex ) {
								$error = $this->Cakeular->error( 'failure','Invalid Request Method : ' . $ex->getMessage() );
								$roles = array(
									'Role' => $error
								);
							}
						} else {
							$parentObj = '';
							if(isset($this->request->query["parentObj"])) {
						    	$parentObj 	= $this->request->query["parentObj"];
						    }
						    $parentId = '';
						    if(isset($this->request->query["parentId"])) {
						    	$parentId	= $this->request->query["parentId"];
						    }
						    $this->Paginator->settings = array(
						    	'page' => $this->request->query["page"],
						        'limit' => $this->request->query["count"]
						    );
						    
						    //$roles = $this->Paginator->paginate('Role');
						    
						    $conditions = array();

						    if($parentObj != '') {
						    	$conditions = array("`" . $parentObj . '`.`id` =' => $parentId);
						    }

	            			// CHANGE FOR THE DESIRED OUTPUT FIELDS ARRAY HERE...
						    $fields = array(
								'Role.createdAt',
								'Role.updatedAt',
								'Role.createdBy',
								'Role.updatedBy',
								'Role.name',
								'Role.lov_role_status',
								'Role.description',
								'Role.id',
							);
					        $this->paginate = array(
					            'fields' => $fields,
					            'conditions' => $conditions
					        );		
			       			$this->Table->emptyElements = 0;
			       			// Change fields here...
					        $this->Table->fields = array($fields);

						    $roles = $this->Table->getResponse();
						}

						$this->set(compact('roles','id'));
					} elseif(!$this->Role->exists($id)){
						$error = $this->Cakeular->error('failure','The Role was not found');
						$role = array(
							'Role' => $error
						);
						$this->set(compact('role','id'));
					} else {
						$role = $this->Role->find('first', array('conditions' => array('Role.' . $this->Role->primaryKey => $id)));
						$this->set(compact('role','id'));
					}
					break;
				case 'POST':
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$roles = array(
							'Role' => $error
						);
						$this->set(compact('roles'));
						break;
					}
					$this->Role->create();
					try {
						if ($this->Role->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Role was added');
							$roles = array(
								'Role' => $message,
								'id' => $this->Role->getLastInsertID()
							);
							$this->set(compact('roles'));
						} else {
							$error = $this->Cakeular->error('failure','The Role was not saved');
							$roles = array(
								'Role' => $error,
								'validationErrors' => $this->Role->validationErrors
							);
							$this->set(compact('roles'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$roles = array('Role' => $error );
						$this->set(compact('roles','id'));
					}					
					break;
				case 'PUT':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$roles = array(
							'Role' => $error
						);
						$this->set(compact('roles'));
						break;
					}
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$roles = array(
							'Role' => $error
						);
						$this->set(compact('roles'));
						break;
					}
					try {
						if ($this->Role->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Role was updated');
							$role = array(
								'Role' => $message
							);
							$this->set(compact('role','id'));
						} else {
							$error = $this->Cakeular->error('failure','The Role was not saved');
							$role = array(
								'Role' => $error,
								'validationErrors' => $this->Role->validationErrors
							);
							$this->set(compact('role','id'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$role = array('Role' => $error );
						$this->set(compact('role','id'));
					}					
					break;
				case 'DELETE':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$roles = array(
							'Role' => $error
						);
						$this->set(compact('roles'));
						break;
					}
					$this->Role->id = $id;
					if ($this->Role->delete()) {
						$message = $this->Cakeular->message('success','The Role was deleted');
						$role = array(
							'Role' => $message
						);
					} else {
						$error = $this->Cakeular->error('failure','The Role was not deleted');
						$role = array(
							'Role' => $error
						);
					}
					$this->set(compact('role','id'));
					break;
				default:
					$error = $this->Cakeular->error('failure','Invalid Request Method');
					$role = array(
						'Role' => $error
					);
					$this->set(compact('role'));
					break;
			}
			$this->layout = 'ajax';
		}

	}
