<?php
	App::uses('AppController', 'Controller');

	/**
	 * Workstations Controller
	 *
	 * @property Workstation $Workstation
	 * @property PaginatorComponent $Paginator
	 */
	class WorkstationsController extends AppController {

		/**
		 * Components
		 *
		 * @var array
		 */
		public $components = array('Paginator', 'Cakeular.Cakeular', 'Table');

		/**
		 * index method
		 *
		 * @return void
		 */
		public function index() {
			$this->layout = 'Cakeular.angular';
		}

		/**
		 * JSON API method
		 * generated by mcred/Cakeular Plugin
		 *
		 * @link          https://github.com/mcred/Cakeular
		 *
		 * @return void
		 * @throws exception
		 */
		public function api($id = null) {
			$method = isset($this->request->query["method"]) ? $this->request->query["method"]:null;
			$params = isset($this->request->query["params"]) ? $this->request->query["params"]:null;
			
			switch ($this->request->method()) {
				case 'GET':
					if (!$id) {

						if( isset($this->request->query["parent_field"]) && isset($this->request->query["parent_value"]) ) {
							try {
								$parentField = $this->request->query["parent_field"];
								$parentValue = $this->request->query["parent_value"];

								$this->Workstation->recursive = -1;
								$workstations = $this->Workstation->find('all', array(
									'conditions' => array(
										'Workstation.'. $parentField . ' LIKE ' => '%' . $parentValue . '%'
									)
								));
							}
							catch(Exception $ex) {
								$error = $this->Cakeular->error('failure',$ex->getMessage());
								$workstations = array('Workstation' => $error );
							}
						} 
		 				elseif($method != null)
						{
							try{
								$workstations = $this->$method( $params );				
								$this->set(compact('workstations'));
							}
							catch( Exception $ex ) {
								$error = $this->Cakeular->error( 'failure','Invalid Request Method : ' . $ex->getMessage() );
								$workstations = array(
									'Workstation' => $error
								);
							}
						} else {
							$parentObj = '';
							if(isset($this->request->query["parentObj"])) {
						    	$parentObj 	= $this->request->query["parentObj"];
						    }
						    $parentId = '';
						    if(isset($this->request->query["parentId"])) {
						    	$parentId	= $this->request->query["parentId"];
						    }
						    $this->Paginator->settings = array(
						    	'page' => $this->request->query["page"],
						        'limit' => $this->request->query["count"]
						    );
						    
						    //$workstations = $this->Paginator->paginate('Workstation');
						    
						    $conditions = array();

						    if($parentObj != '') {
						    	$conditions = array("`" . $parentObj . '`.`id` =' => $parentId);
						    }

	            			// CHANGE FOR THE DESIRED OUTPUT FIELDS ARRAY HERE...
						    $fields = array(
								'Workstation.createdAt',
								'Workstation.updatedAt',
								'Workstation.createdBy',
								'Workstation.updatedBy',
								'Workstation.name',
								'Workstation.employeeNumber',
								'Workarea.name',
								'Workstation.workarea_id',
								'Workstation.lov_workstation_status',
								'Parent.name',
								'Workstation.parent_id',
								'Building.name',
								'Workstation.building_id',
								'Workstation.description',
								'Workstation.id',
							);
					        $this->paginate = array(
					            'fields' => $fields,
					            'conditions' => $conditions
					        );		
			       			$this->Table->emptyElements = 0;
			       			// Change fields here...
					        $this->Table->fields = array($fields);

						    $workstations = $this->Table->getResponse();
						}

						$this->set(compact('workstations','id'));
					} elseif(!$this->Workstation->exists($id)){
						$error = $this->Cakeular->error('failure','The Workstation was not found');
						$workstation = array(
							'Workstation' => $error
						);
						$this->set(compact('workstation','id'));
					} else {
						$workstation = $this->Workstation->find('first', array('conditions' => array('Workstation.' . $this->Workstation->primaryKey => $id)));
						$this->set(compact('workstation','id'));
					}
					break;
				case 'POST':
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$workstations = array(
							'Workstation' => $error
						);
						$this->set(compact('workstations'));
						break;
					}
					$this->Workstation->create();
					try {
						if ($this->Workstation->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Workstation was added');
							$workstations = array(
								'Workstation' => $message,
								'id' => $this->Workstation->getLastInsertID()
							);
							$this->set(compact('workstations'));
						} else {
							$error = $this->Cakeular->error('failure','The Workstation was not saved');
							$workstations = array(
								'Workstation' => $error,
								'validationErrors' => $this->Workstation->validationErrors
							);
							$this->set(compact('workstations'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$workstations = array('Workstation' => $error );
						$this->set(compact('workstations','id'));
					}					
					break;
				case 'PUT':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$workstations = array(
							'Workstation' => $error
						);
						$this->set(compact('workstations'));
						break;
					}
					if(!isset($this->request->data['body'])){
						$error = $this->Cakeular->error('failure','POST body is missing');
						$workstations = array(
							'Workstation' => $error
						);
						$this->set(compact('workstations'));
						break;
					}
					try {
						if ($this->Workstation->save(json_decode($this->request->data['body'], true))) {
							$message = $this->Cakeular->message('success','The Workstation was updated');
							$workstation = array(
								'Workstation' => $message
							);
							$this->set(compact('workstation','id'));
						} else {
							$error = $this->Cakeular->error('failure','The Workstation was not saved');
							$workstation = array(
								'Workstation' => $error,
								'validationErrors' => $this->Workstation->validationErrors
							);
							$this->set(compact('workstation','id'));
						}
					}
					catch(Exception $ex) {
						$error = $this->Cakeular->error('failure',$ex->getMessage());
						$workstation = array('Workstation' => $error );
						$this->set(compact('workstation','id'));
					}					
					break;
				case 'DELETE':
					if(!$id){
						$error = $this->Cakeular->error('failure','ID parameter missing');
						$workstations = array(
							'Workstation' => $error
						);
						$this->set(compact('workstations'));
						break;
					}
					$this->Workstation->id = $id;
					if ($this->Workstation->delete()) {
						$message = $this->Cakeular->message('success','The Workstation was deleted');
						$workstation = array(
							'Workstation' => $message
						);
					} else {
						$error = $this->Cakeular->error('failure','The Workstation was not deleted');
						$workstation = array(
							'Workstation' => $error
						);
					}
					$this->set(compact('workstation','id'));
					break;
				default:
					$error = $this->Cakeular->error('failure','Invalid Request Method');
					$workstation = array(
						'Workstation' => $error
					);
					$this->set(compact('workstation'));
					break;
			}
			$this->layout = 'ajax';
		}

	}
